import { useEffect, useRef, useState } from 'react';
import { Edit3, Eye, LayoutDashboard } from 'lucide-react';
import Navbar from './Navbar'; import Hero from './Hero'; import BrandIntro from './BrandIntro'; import OrderForm from './OrderForm'; import ServiceComparison from './ServiceComparison'; import BrandProductionCards from './BrandProductionCards'; import HowToOrder from './HowToOrder'; import PortfolioGallery from './PortfolioGallery'; import ClientProof from './ClientProof'; import Footer from './Footer'; import FullContentEditor from './FullContentEditor'; import { supabase } from '../lib/supabase';

function InlinePreview() { const ref = useRef<HTMLDivElement>(null); useEffect(() => { const root = ref.current; if (!root) return; const nodes = Array.from(root.querySelectorAll<HTMLElement>('h1,h2,h3,h4,p')); nodes.forEach((node, index) => { node.contentEditable = 'true'; node.dataset.editIndex = String(index); node.classList.add('outline-dashed', 'outline-1', 'outline-transparent', 'hover:outline-red-500', 'focus:outline-red-600'); }); const save = async (event: Event) => { const node = event.currentTarget as HTMLElement; if (!supabase || !node.innerText.trim()) return; await supabase.from('site_sections').upsert({ id: 'visual-edits', title: 'Visual edits', content: { [node.dataset.editIndex || '0']: node.innerText }, updated_at: new Date().toISOString() }); }; nodes.forEach((node) => node.addEventListener('blur', save)); return () => nodes.forEach((node) => { node.removeEventListener('blur', save); node.contentEditable = 'false'; }); }, []); return <div ref={ref}><Navbar /><main><Hero /><BrandIntro /><OrderForm /><ServiceComparison /><BrandProductionCards /><HowToOrder /><PortfolioGallery /><ClientProof /></main><Footer /></div>; }

export default function AdminVisualEditor() {
  const [preview, setPreview] = useState(true);
  if (preview) return <div className="min-h-screen bg-white"><div className="sticky top-0 z-[60] flex items-center justify-between bg-red-700 px-4 py-3 text-sm font-bold text-white"><span className="inline-flex items-center gap-2"><Eye className="h-4 w-4" /> Klik teks untuk mengedit langsung</span><button onClick={() => setPreview(false)} className="rounded-lg bg-white px-3 py-2 text-red-700">Kembali ke editor</button></div><div className="font-['Plus_Jakarta_Sans',sans-serif]"><InlinePreview /></div></div>;
  return <div className="relative"><button type="button" onClick={() => setPreview(true)} className="fixed bottom-5 right-5 z-50 inline-flex items-center gap-2 rounded-full bg-neutral-950 px-5 py-3 text-sm font-bold text-white shadow-xl"><Eye className="h-4 w-4" /> Preview landing page</button><div className="flex items-center gap-2 border-b border-neutral-200 bg-white px-5 py-3 text-sm font-bold text-neutral-950"><LayoutDashboard className="h-4 w-4" /> Editor visual landing page <span className="ml-auto inline-flex items-center gap-1 text-xs text-neutral-500"><Edit3 className="h-3.5 w-3.5" /> Pilih section di panel editor</span></div><FullContentEditor /></div>;
}
