import { useState } from 'react';
import { X } from 'lucide-react';
import { PORTFOLIO_ITEMS } from '../data/content';
import { PortfolioItem } from '../types';

const categories = [{ id: 'all', label: 'Semua Karya' }, { id: 'dtf', label: 'Sablon DTF' }, { id: 'manual', label: 'Sablon Manual' }];

export default function PortfolioGallery() {
  const [activeCategory, setActiveCategory] = useState('all');
  const [previewItem, setPreviewItem] = useState<PortfolioItem | null>(null);
  const filteredItems = activeCategory === 'all' ? PORTFOLIO_ITEMS : PORTFOLIO_ITEMS.filter((item) => item.category === activeCategory);
  return <section id="portofolio" className="border-b border-neutral-200 bg-neutral-100 py-14 md:py-20" aria-labelledby="portfolio-title"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><h2 id="portfolio-title" className="text-3xl font-black tracking-tight text-neutral-950 sm:text-5xl">Hasil karya kami.</h2><div className="flex flex-wrap gap-2" role="group" aria-label="Filter kategori portofolio">{categories.map((category) => <button key={category.id} type="button" onClick={() => setActiveCategory(category.id)} aria-pressed={activeCategory === category.id} className={`min-h-10 rounded-full border px-4 text-xs font-bold transition ${activeCategory === category.id ? 'border-neutral-950 bg-neutral-950 text-white' : 'border-neutral-300 bg-white text-neutral-700 hover:border-neutral-950 hover:text-neutral-950'}`}>{category.label}</button>)}</div></div><div className="grid auto-rows-[150px] grid-cols-2 gap-3 sm:auto-rows-[190px] sm:grid-cols-4 sm:gap-4">{filteredItems.map((item, index) => <button key={item.id} type="button" onClick={() => setPreviewItem(item)} aria-label={`Lihat hasil karya ${index + 1}`} className={`group relative overflow-hidden rounded-2xl bg-neutral-200 text-left focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-neutral-950 ${index % 5 === 0 ? 'col-span-2 row-span-2' : index % 4 === 0 ? 'row-span-2' : 'row-span-1'}`}><img src={item.image} alt="" loading="lazy" decoding="async" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></button>)}</div></div>{previewItem && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4" role="dialog" aria-modal="true" aria-label="Preview hasil karya" onClick={() => setPreviewItem(null)}><div className="relative max-h-[90vh] max-w-5xl" onClick={(event) => event.stopPropagation()}><img src={previewItem.image} alt={previewItem.title} className="max-h-[85vh] w-auto rounded-2xl object-contain" /><button type="button" onClick={() => setPreviewItem(null)} aria-label="Tutup preview" className="absolute -right-3 -top-3 flex h-10 w-10 items-center justify-center rounded-full bg-white text-neutral-950 shadow-lg"><X className="h-5 w-5" /></button></div></div>}</section>;
}
