import { useState } from 'react';
import { ArrowLeft, BarChart3, RotateCcw, Save } from 'lucide-react';
import { WHATSAPP_ROTATOR_NUMBERS } from '../data/content';
import { getSiteSettings, saveSiteSettings } from '../data/siteSettings';

const HITS_KEY = 'gudang-planet-whatsapp-rotator-hits';
const readHits = () => { try { return JSON.parse(localStorage.getItem(HITS_KEY) || '{}') as Record<string, number>; } catch { return {}; } };

export default function WhatsAppRotatorEditor() {
  const [settings, setSettings] = useState(getSiteSettings()); const [numbers, setNumbers] = useState(() => { try { return JSON.parse(localStorage.getItem('gudang-planet-whatsapp-rotator-numbers') || 'null') || WHATSAPP_ROTATOR_NUMBERS; } catch { return WHATSAPP_ROTATOR_NUMBERS; } }); const [hits, setHits] = useState(readHits()); const [saved, setSaved] = useState(false);
  const save = () => { localStorage.setItem('gudang-planet-whatsapp-rotator-numbers', JSON.stringify(numbers)); saveSiteSettings(settings); setSaved(true); setTimeout(() => setSaved(false), 2200); };
  const resetHits = () => { localStorage.removeItem(HITS_KEY); setHits({}); };
  return <main className="min-h-screen bg-neutral-100 px-4 py-8 text-neutral-950 sm:px-6"><div className="mx-auto max-w-4xl"><div className="mb-8 flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-neutral-500">Pengaturan CTA</p><h1 className="mt-2 text-3xl font-black">Rotator WhatsApp</h1><p className="mt-2 text-sm text-neutral-600">Kelola nomor CS dan lihat pembagian hit CTA.</p></div><a href="/" className="inline-flex items-center gap-2 rounded-xl border border-neutral-300 bg-white px-4 py-3 text-sm font-bold"><ArrowLeft className="h-4 w-4" /> Website</a></div><section className="rounded-3xl border border-neutral-200 bg-white p-5 shadow-sm sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black">Nomor CS rotator</h2><p className="mt-1 text-sm text-neutral-600">Leads dibagi berurutan ke nomor aktif.</p></div><BarChart3 className="h-6 w-6 text-neutral-500" /></div><div className="mt-6 space-y-3">{numbers.map((number: string, index: number) => <div key={index} className="flex items-center gap-3 rounded-2xl border border-neutral-200 p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-neutral-950 text-sm font-bold text-white">{index + 1}</span><input value={number} inputMode="tel" onChange={(e) => setNumbers((items: string[]) => items.map((item, i) => i === index ? e.target.value.replace(/\D/g, '') : item))} className="min-w-0 flex-1 rounded-xl border border-neutral-300 px-3 py-2 font-mono text-sm" /><span className="rounded-full bg-neutral-100 px-3 py-1 text-xs font-bold">{hits[number] || 0} hit</span></div>)}</div><div className="mt-6 rounded-2xl bg-neutral-950 p-5 text-white"><p className="text-xs text-neutral-400">Nomor default CTA</p><input value={settings.whatsappNumber} onChange={(e) => setSettings({ ...settings, whatsappNumber: e.target.value.replace(/\D/g, '') })} className="mt-2 w-full rounded-xl border border-white/20 bg-white/10 px-3 py-3 font-mono text-sm text-white outline-none" /></div><div className="mt-6 flex flex-wrap gap-3"><button onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-red-700 px-5 py-3 text-sm font-bold text-white"><Save className="h-4 w-4" /> {saved ? 'Tersimpan' : 'Simpan pengaturan'}</button><button onClick={resetHits} className="inline-flex items-center gap-2 rounded-xl border border-neutral-300 px-5 py-3 text-sm font-bold"><RotateCcw className="h-4 w-4" /> Reset statistik</button></div></section></div></main>;
}
